#!/usr/bin/env python3
"""
Migration Validation Tool

Compares data between EMR (S3/Hive) and Databricks (Unity Catalog)
to validate migration correctness.

Usage:
    python validate_migration.py --config validation_config.json
    python validate_migration.py --source-table "parquet.`s3://bucket/path`" \
                                  --target-table "catalog.schema.table" \
                                  --profile my-databricks-profile

Prerequisites:
    pip install databricks-sdk pyspark  (for local validation)
    Or run directly on Databricks as a notebook
"""

import argparse
import json
import sys
from dataclasses import asdict, dataclass
from datetime import datetime
from typing import Any


@dataclass
class ValidationResult:
    """Result of a single validation check."""
    check_name: str
    status: str  # PASS, FAIL, WARN, SKIP
    source_value: Any = None
    target_value: Any = None
    difference: Any = None
    details: str = ""


@dataclass
class ValidationReport:
    """Complete validation report."""
    timestamp: str
    source_table: str
    target_table: str
    overall_status: str  # PASS, FAIL
    checks: list[dict]
    summary: dict


def generate_validation_sql(
    source_table: str,
    target_table: str,
    key_columns: list[str] | None = None,
    numeric_columns: list[str] | None = None,
    sample_size: int = 1000,
) -> dict[str, str]:
    """Generate SQL queries for validation checks."""
    queries = {}

    # 1. Row count comparison
    queries["row_count_source"] = f"SELECT COUNT(*) as cnt FROM {source_table}"
    queries["row_count_target"] = f"SELECT COUNT(*) as cnt FROM {target_table}"

    # 2. Schema comparison
    queries["schema_source"] = f"DESCRIBE {source_table}"
    queries["schema_target"] = f"DESCRIBE {target_table}"

    # 3. Null count per column
    queries["null_analysis_source"] = f"""
SELECT
  COUNT(*) as total_rows,
  {', '.join(f'SUM(CASE WHEN `{col}` IS NULL THEN 1 ELSE 0 END) as null_{col}' for col in (key_columns or ['*']))}
FROM {source_table}
""".strip()

    queries["null_analysis_target"] = f"""
SELECT
  COUNT(*) as total_rows,
  {', '.join(f'SUM(CASE WHEN `{col}` IS NULL THEN 1 ELSE 0 END) as null_{col}' for col in (key_columns or ['*']))}
FROM {target_table}
""".strip()

    # 4. Aggregate validation on numeric columns
    if numeric_columns:
        agg_exprs = []
        for col in numeric_columns:
            agg_exprs.extend([
                f"SUM(`{col}`) as sum_{col}",
                f"AVG(`{col}`) as avg_{col}",
                f"MIN(`{col}`) as min_{col}",
                f"MAX(`{col}`) as max_{col}",
            ])
        agg_str = ",\n  ".join(agg_exprs)
        queries["aggregates_source"] = f"SELECT\n  {agg_str}\nFROM {source_table}"
        queries["aggregates_target"] = f"SELECT\n  {agg_str}\nFROM {target_table}"

    # 5. Sample data comparison
    if key_columns:
        order_by = ", ".join(f"`{col}`" for col in key_columns)
        queries["sample_source"] = f"SELECT * FROM {source_table} ORDER BY {order_by} LIMIT {sample_size}"
        queries["sample_target"] = f"SELECT * FROM {target_table} ORDER BY {order_by} LIMIT {sample_size}"
    else:
        queries["sample_source"] = f"SELECT * FROM {source_table} LIMIT {sample_size}"
        queries["sample_target"] = f"SELECT * FROM {target_table} LIMIT {sample_size}"

    # 6. Distinct count on key columns
    if key_columns:
        for col in key_columns:
            queries[f"distinct_{col}_source"] = f"SELECT COUNT(DISTINCT `{col}`) as cnt FROM {source_table}"
            queries[f"distinct_{col}_target"] = f"SELECT COUNT(DISTINCT `{col}`) as cnt FROM {target_table}"

    # 7. Hash-based row comparison (for exact match verification)
    if key_columns:
        all_cols = ", ".join(f"CAST(`{col}` AS STRING)" for col in key_columns)
        queries["hash_source"] = f"""
SELECT MD5(CONCAT_WS('|', {all_cols})) as row_hash, COUNT(*) as cnt
FROM {source_table}
GROUP BY 1
ORDER BY 1
LIMIT 100
""".strip()
        queries["hash_target"] = f"""
SELECT MD5(CONCAT_WS('|', {all_cols})) as row_hash, COUNT(*) as cnt
FROM {target_table}
GROUP BY 1
ORDER BY 1
LIMIT 100
""".strip()

    return queries


def generate_validation_notebook(
    source_table: str,
    target_table: str,
    key_columns: list[str] | None = None,
    numeric_columns: list[str] | None = None,
) -> str:
    """Generate a Databricks notebook for validation."""
    key_cols_str = json.dumps(key_columns or [])
    num_cols_str = json.dumps(numeric_columns or [])

    notebook = f"""# Databricks notebook source
# Migration Validation: {source_table} → {target_table}
# Generated by validate_migration.py

# COMMAND ----------

# Configuration
SOURCE_TABLE = "{source_table}"
TARGET_TABLE = "{target_table}"
KEY_COLUMNS = {key_cols_str}
NUMERIC_COLUMNS = {num_cols_str}

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Row Count Comparison

# COMMAND ----------

source_count = spark.sql(f"SELECT COUNT(*) as cnt FROM {{SOURCE_TABLE}}").first().cnt
target_count = spark.sql(f"SELECT COUNT(*) as cnt FROM {{TARGET_TABLE}}").first().cnt

print(f"Source rows: {{source_count:,}}")
print(f"Target rows: {{target_count:,}}")
print(f"Difference:  {{target_count - source_count:,}}")

if source_count == target_count:
    print("✓ PASS: Row counts match")
else:
    pct_diff = abs(target_count - source_count) / max(source_count, 1) * 100
    print(f"✗ FAIL: Row counts differ by {{pct_diff:.2f}}%")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Schema Comparison

# COMMAND ----------

source_schema = spark.sql(f"DESCRIBE {{SOURCE_TABLE}}").toPandas()
target_schema = spark.sql(f"DESCRIBE {{TARGET_TABLE}}").toPandas()

# Compare column names and types
source_cols = set(zip(source_schema['col_name'], source_schema['data_type']))
target_cols = set(zip(target_schema['col_name'], target_schema['data_type']))

only_in_source = source_cols - target_cols
only_in_target = target_cols - source_cols

if not only_in_source and not only_in_target:
    print("✓ PASS: Schemas match")
else:
    if only_in_source:
        print(f"✗ Columns only in source: {{only_in_source}}")
    if only_in_target:
        print(f"✗ Columns only in target: {{only_in_target}}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Aggregate Validation

# COMMAND ----------

if NUMERIC_COLUMNS:
    for col in NUMERIC_COLUMNS:
        source_agg = spark.sql(f"SELECT SUM(`{{col}}`) as s, AVG(`{{col}}`) as a, MIN(`{{col}}`) as mn, MAX(`{{col}}`) as mx FROM {{SOURCE_TABLE}}").first()
        target_agg = spark.sql(f"SELECT SUM(`{{col}}`) as s, AVG(`{{col}}`) as a, MIN(`{{col}}`) as mn, MAX(`{{col}}`) as mx FROM {{TARGET_TABLE}}").first()

        print(f"\\nColumn: {{col}}")
        print(f"  SUM  - Source: {{source_agg.s}}, Target: {{target_agg.s}}, Match: {{source_agg.s == target_agg.s}}")
        print(f"  AVG  - Source: {{source_agg.a}}, Target: {{target_agg.a}}")
        print(f"  MIN  - Source: {{source_agg.mn}}, Target: {{target_agg.mn}}, Match: {{source_agg.mn == target_agg.mn}}")
        print(f"  MAX  - Source: {{source_agg.mx}}, Target: {{target_agg.mx}}, Match: {{source_agg.mx == target_agg.mx}}")
else:
    print("No numeric columns specified for aggregate validation")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Null Analysis

# COMMAND ----------

source_df = spark.table(SOURCE_TABLE)
target_df = spark.table(TARGET_TABLE)

print("Null counts per column:")
print(f"{{' Column':<30}} {{'Source Nulls':>15}} {{'Target Nulls':>15}} {{'Match':>8}}")
print("-" * 70)

for col in source_df.columns:
    if col in [c.name for c in target_df.schema]:
        src_nulls = source_df.filter(f"`{{col}}` IS NULL").count()
        tgt_nulls = target_df.filter(f"`{{col}}` IS NULL").count()
        match = "✓" if src_nulls == tgt_nulls else "✗"
        print(f"{{col:<30}} {{src_nulls:>15,}} {{tgt_nulls:>15,}} {{match:>8}}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Sample Data Comparison

# COMMAND ----------

if KEY_COLUMNS:
    order_expr = ", ".join(f"`{{c}}`" for c in KEY_COLUMNS)
    source_sample = spark.sql(f"SELECT * FROM {{SOURCE_TABLE}} ORDER BY {{order_expr}} LIMIT 10")
    target_sample = spark.sql(f"SELECT * FROM {{TARGET_TABLE}} ORDER BY {{order_expr}} LIMIT 10")
else:
    source_sample = spark.sql(f"SELECT * FROM {{SOURCE_TABLE}} LIMIT 10")
    target_sample = spark.sql(f"SELECT * FROM {{TARGET_TABLE}} LIMIT 10")

print("Source sample:")
display(source_sample)

print("Target sample:")
display(target_sample)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Summary

# COMMAND ----------

print("=" * 50)
print("MIGRATION VALIDATION SUMMARY")
print("=" * 50)
print(f"Source: {{SOURCE_TABLE}}")
print(f"Target: {{TARGET_TABLE}}")
print(f"Row count match: {{source_count == target_count}}")
print(f"Schema match: {{not only_in_source and not only_in_target}}")
print()
if source_count == target_count and not only_in_source and not only_in_target:
    print("OVERALL: ✓ PASS")
else:
    print("OVERALL: ✗ FAIL - Review details above")
"""
    return notebook


def main():
    parser = argparse.ArgumentParser(
        description="Generate migration validation queries and notebooks"
    )
    parser.add_argument("--source-table", help="Source table (EMR/S3 path or Hive table)")
    parser.add_argument("--target-table", help="Target table (Unity Catalog)")
    parser.add_argument(
        "--key-columns", nargs="+", help="Key columns for ordering and comparison"
    )
    parser.add_argument(
        "--numeric-columns", nargs="+", help="Numeric columns for aggregate validation"
    )
    parser.add_argument(
        "--mode",
        choices=["sql", "notebook"],
        default="notebook",
        help="Output mode: SQL queries or Databricks notebook",
    )
    parser.add_argument("--config", help="JSON config file with table pairs")
    parser.add_argument("--output", default="-", help="Output file (- for stdout)")
    args = parser.parse_args()

    if args.config:
        with open(args.config) as f:
            config = json.load(f)
        source = config["source_table"]
        target = config["target_table"]
        key_cols = config.get("key_columns")
        num_cols = config.get("numeric_columns")
    elif args.source_table and args.target_table:
        source = args.source_table
        target = args.target_table
        key_cols = args.key_columns
        num_cols = args.numeric_columns
    else:
        parser.error("Specify --source-table/--target-table or --config")

    if args.mode == "sql":
        queries = generate_validation_sql(source, target, key_cols, num_cols)
        output = "\n\n".join(
            f"-- {name}\n{sql}" for name, sql in queries.items()
        )
    else:
        output = generate_validation_notebook(source, target, key_cols, num_cols)

    if args.output == "-":
        print(output)
    else:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Output written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
