command:
  - python
  - app.py
env:
  - name: DATABRICKS_HOST
    valueFrom: host
  - name: DATABRICKS_SQL_WAREHOUSE_ID
    value: "80bb9cfd8c6e5b05"
resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "80bb9cfd8c6e5b05"
      permission: CAN_USE
