// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    cluster_hosts: {
        name: "cluster_hosts";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          database: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          node_count: number;
          /** @sqlType BIGINT */
          total_vcores: number;
          /** @sqlType DOUBLE */
          avg_vcores_per_node: number;
          /** @sqlType DOUBLE */
          total_mem_gb: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** INT - use sql.int() */
          max_month_num: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
    observation_window: {
        name: "observation_window";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          database: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          distinct_days: number;
          /** @sqlType DECIMAL(33,12) */
          span_days: number;
          /** @sqlType BIGINT */
          apps: number;
        }>;
      };
    peak_workload: {
        name: "peak_workload";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          database: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType DOUBLE */
          peak_memory_gb: number;
          /** @sqlType DOUBLE */
          peak_vcores: number;
          /** @sqlType DOUBLE */
          avg_memory_gb: number;
          /** @sqlType DOUBLE */
          avg_vcores: number;
        }>;
      };
    profiler_catalogs: {
        name: "profiler_catalogs";
        parameters: Record<string, never>;
        result: Array<{
          /** Name of the catalog. */
          catalog_name: string;
        }>;
      };
    profiler_schemas: {
        name: "profiler_schemas";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
        };
        result: Array<{
          /** Name of the schema. */
          schema_name: string;
        }>;
      };
    workload_by_type: {
        name: "workload_by_type";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          database: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          job_type: string;
          /** @sqlType BIGINT */
          total_jobs: number;
          /** @sqlType DOUBLE */
          total_memory_gb_hours: number;
        }>;
      };
  }
}
