#!/usr/bin/env python3
"""Generate a human-readable README.md for each SSA offering from its catalog-listing.yml.

One source (catalog-listing.yml) -> generated output (<category>/<slug>/README.md). People
read the README instead of raw YAML; GitHub renders it, and Sage's crawler gets clean prose
too. Marked GENERATED -- never hand-edit; edit the listing and regenerate.

This is the HUMAN-facing output. It does NOT feed Isaac's ASQ creation -- that path reads the
gtm-asq plugin's own fe_catalog.yaml, which is a separate (Azure-Yu-owned) sync. The README
tells a human which hashtag to put on their ASQ; it does not make any agent auto-map anything.

Dependency-free (stock python3). Reuses gen_sage_manifest's top-level scalar parser and adds
two small readers: one for the `links:` nested map, one for the `demo_description:` block scalar.

Only generates OFFERING-level READMEs (<category>/<slug>/README.md). Category-level READMEs
(e.g. data-governance/README.md) are hand-maintained indexes and are left untouched.

Usage:  python3 scripts/gen_readme.py [--check]
  (no args)  write <category>/<slug>/README.md for every active offering
  --check    exit non-zero if any README is out of date (for CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_sage_manifest import (  # noqa: E402
    REPO,
    discover_offerings,
    read_listing,
)

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/gen_readme.py -- do not edit by hand. "
    "Edit catalog-listing.yml and regenerate. -->"
)


def read_block(path: Path, key: str) -> str:
    """Return the dedented body of a top-level `key: |` block scalar, or ''."""
    lines = path.read_text(encoding="utf-8").splitlines()
    n = len(lines)
    i = 0
    found = False
    while i < n:
        raw = lines[i]
        i += 1
        s = raw.strip()
        if raw[:1] in (" ", "\t") or ":" not in s or s.startswith("#"):
            continue
        k, _, v = s.partition(":")
        if k.strip() == key:
            if v.strip()[:1] not in ("|", ">"):
                return ""  # scalar, not a block
            found = True
            break
    if not found:
        return ""

    body: list[str] = []
    indent: int | None = None
    while i < n:
        raw = lines[i]
        if raw.strip() == "":
            body.append("")
            i += 1
            continue
        cur = len(raw) - len(raw.lstrip())
        if cur == 0:  # back to column 0 -> block is over
            break
        if indent is None:
            indent = cur
        body.append(raw[indent:] if len(raw) >= indent else raw.lstrip())
        i += 1
    while body and body[-1] == "":
        body.pop()
    return "\n".join(body)


def read_map(path: Path, key: str) -> dict[str, str]:
    """Return a top-level nested `key:` map as {child_key: value}."""
    lines = path.read_text(encoding="utf-8").splitlines()
    n = len(lines)
    i = 0
    out: dict[str, str] = {}
    while i < n:
        raw = lines[i]
        i += 1
        s = raw.strip()
        if raw[:1] in (" ", "\t") or ":" not in s or s.startswith("#"):
            continue
        k, _, v = s.partition(":")
        if k.strip() == key and v.strip() == "":
            while i < n:
                nxt = lines[i]
                if nxt.strip() == "":
                    i += 1
                    continue
                if nxt[:1] not in (" ", "\t"):  # back to column 0
                    break
                ls = nxt.strip()
                if not ls.startswith("#") and ":" in ls:
                    ck, _, cv = ls.partition(":")
                    out[ck.strip()] = cv.strip()
                i += 1
            break
    return out


def render_readme(listing: Path) -> str:
    fm = read_listing(listing)
    offering_dir = listing.parent
    slug = offering_dir.name
    title = fm.get("title") or slug

    parts = [GENERATED_HEADER, "", f"# {title}", ""]

    rows: list[tuple[str, str]] = []
    for label, key in (
        ("Status", "status"),
        ("Owner", "demo_owner"),
        ("Products", "products"),
        ("Product lines", "product_lines"),
        ("Last certified", "last_certified"),
    ):
        val = fm.get(key)
        if val:
            rows.append((label, str(val)))
    tags = fm.get("tags")
    if isinstance(tags, list) and tags:
        rows.append(("Tags", ", ".join(tags)))
    links = read_map(listing, "links")
    if links:
        rows.append(("Links", " · ".join(f"[{k}]({v})" for k, v in links.items())))
    # Human ASQ-filing hint: the hashtag is the stable join key across repo/Sage/ASQ.
    rows.append(("Request via", f"file an ASQ (go/gethelp) and tag `#ssa-offering #{slug}`"))

    parts.append("| | |")
    parts.append("|---|---|")
    for label, val in rows:
        parts.append(f"| {label} | {val} |")
    parts.append("")

    body = read_block(listing, "demo_description")
    if body:
        parts.extend(["---", "", body, ""])

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    offerings = discover_offerings()
    if not offerings:
        print("No offerings found", file=sys.stderr)
        return 1

    stale: list[str] = []
    written = 0
    for listing in offerings:
        out_path = listing.parent / "README.md"
        rendered = render_readme(listing)
        if check:
            current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if current != rendered:
                stale.append(str(out_path.relative_to(REPO)))
        else:
            out_path.write_text(rendered, encoding="utf-8")
            written += 1

    if check:
        if stale:
            print("READMEs out of date -- run scripts/gen_readme.py:", file=sys.stderr)
            for s in stale:
                print(f"  - {s}", file=sys.stderr)
            return 1
        print(f"READMEs up to date ({len(offerings)} offerings)")
        return 0
    print(f"Wrote {written} README.md files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
